### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by srem1** [ltratt/rustbfs#1]
cargo run --release --bin interp1 hello.bf
   Compiling interp1 v0.1.0 (/home/ooo/rustbfs/interp1)
    Finished release [optimized] target(s) in 4.53s
     Running `target/release/interp1 hello.bf`
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

i canot find **multitime** program on my system fedora

**Comment by ltratt** [comment]
You'll need to copy and paste "hello world" from the blog post into a `hello.bf` file in the root of the repository for this to work (or download it from elsewhere on the web).

**Comment by srem1** [comment]
you probably need:

0. add file *.bf to repo

1. change web text ;)
